### ISSUE TITLE
line 21, in <module>     crypto_coins = json_data['data'].   KeyError: 'data'

### ISSUE THREAD

**Issue by mahdyledurs** [ahmetk5113/Trading-bot#1]
Hey my friend, 

Tanks for your work! 
But I have a issue with line 21. He can not open the Data so I created a Json but that didn't help. 
Can you help me out?

Thanks

**Comment by Ahmet-Kirmizi** [comment]
have you added your 'X-CMC_PRO_API_KEY'? if not get your coinmarketcap API key from their website.

**Comment by Ahmet-Kirmizi** [comment]
if you are using my original source code there should be no problems. you only have to enter your API key in order to use it.

**Comment by mahdyledurs** [comment]
Thanks buddy I modified a little bit you code was very useful! Keep going

**Comment by Ahmet-Kirmizi** [comment]
you are welcome :),  you can ask me if you have more questions.
